// Render a Walmart order to PDF. Builds a clean HTML template and renders it
// with Playwright (no login, no remote navigation — just setContent + page.pdf).
//
// Failure to render is non-fatal: returns null and the caller continues
// without a PDF. The order_draft is the source of truth, the PDF is just an
// archive copy.

import chromium from "@sparticuz/chromium";
import { chromium as playwrightChromium } from "playwright-core";
import type { WalmartParsed } from "@/lib/walmart/parse-order";

function formatCurrency(amount: number, currency = "USD"): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency,
    minimumFractionDigits: 2,
  }).format(amount);
}

function formatDate(iso: string | null): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleString("en-US", {
    dateStyle: "short",
    timeStyle: "short",
  });
}

function escape(s: string | null | undefined): string {
  if (!s) return "";
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function renderHtml(p: WalmartParsed): string {
  const linesHtml = p.lines
    .map(
      (l) => `
    <tr>
      <td>${escape(l.line_number)}</td>
      <td><code>${escape(l.sku)}</code></td>
      <td>${escape(l.product_name)}</td>
      <td class="num">${l.quantity}</td>
      <td>${escape(l.unit_of_measurement)}</td>
      <td class="num">${formatCurrency(l.unit_price, l.currency)}</td>
      <td class="num">${formatCurrency(l.line_total, l.currency)}</td>
    </tr>`,
    )
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Walmart PO ${escape(p.po_number)}</title>
  <style>
    @page { margin: 0; }
    body {
      font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
      font-size: 11px;
      color: #1a1a1a;
      margin: 0;
      padding: 32px;
      line-height: 1.4;
    }
    .header {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 3px solid #0071ce;
      padding-bottom: 12px;
      margin-bottom: 18px;
    }
    .brand { font-size: 22px; font-weight: 800; color: #0071ce; letter-spacing: -0.5px; }
    .brand small { font-size: 11px; font-weight: 500; color: #666; display: block; margin-top: 2px; }
    .po-block { text-align: right; }
    .po-block .label { font-size: 9px; text-transform: uppercase; color: #666; letter-spacing: 0.5px; }
    .po-block .value { font-size: 14px; font-weight: 700; }

    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; margin-bottom: 18px; }
    .panel {
      border: 1px solid #ddd;
      border-radius: 4px;
      padding: 10px 12px;
      background: #fafafa;
    }
    .panel h3 {
      font-size: 9px;
      text-transform: uppercase;
      color: #666;
      letter-spacing: 0.5px;
      margin: 0 0 6px;
      font-weight: 700;
    }
    .panel p { margin: 1px 0; }
    .panel strong { font-weight: 600; }

    table { width: 100%; border-collapse: collapse; margin-top: 4px; font-size: 10.5px; }
    thead th {
      background: #f0f4fa;
      text-align: left;
      padding: 7px 8px;
      font-size: 9px;
      text-transform: uppercase;
      color: #444;
      font-weight: 700;
      letter-spacing: 0.4px;
      border-bottom: 2px solid #d0d8e4;
    }
    tbody td { padding: 7px 8px; border-bottom: 1px solid #eee; vertical-align: top; }
    tbody td.num { text-align: right; font-variant-numeric: tabular-nums; }
    code { font-family: "SF Mono", Menlo, Consolas, monospace; font-size: 10px; }

    .totals { margin-top: 14px; display: flex; justify-content: flex-end; }
    .totals table { width: 280px; font-size: 11px; }
    .totals td { padding: 4px 8px; }
    .totals tr.grand td { font-weight: 700; font-size: 12.5px; border-top: 2px solid #0071ce; padding-top: 8px; }

    .footer {
      margin-top: 28px;
      font-size: 9px;
      color: #888;
      border-top: 1px solid #eee;
      padding-top: 8px;
    }
  </style>
</head>
<body>
  <div class="header">
    <div>
      <div class="brand">Walmart Marketplace</div>
      <small>Purchase Order · Generated by DocFlow</small>
    </div>
    <div class="po-block">
      <div class="label">PO Number</div>
      <div class="value">${escape(p.po_number)}</div>
      <div class="label" style="margin-top: 6px;">Order Date</div>
      <div>${formatDate(p.order_date)}</div>
    </div>
  </div>

  <div class="grid">
    <div class="panel">
      <h3>Ship To</h3>
      <p><strong>${escape(p.ship_to.name)}</strong></p>
      <p>${escape(p.ship_to.line1)}</p>
      ${p.ship_to.line2 ? `<p>${escape(p.ship_to.line2)}</p>` : ""}
      <p>${escape(p.ship_to.city)}, ${escape(p.ship_to.state)} ${escape(p.ship_to.zip)}</p>
      <p>${escape(p.ship_to.country)}</p>
      ${p.ship_to.phone ? `<p>Phone: ${escape(p.ship_to.phone)}</p>` : ""}
    </div>
    <div class="panel">
      <h3>Order Info</h3>
      <p><strong>Customer Order:</strong> ${escape(p.customer_order_id)}</p>
      <p><strong>Shipping Method:</strong> ${escape(p.shipping_method ?? "—")}</p>
      <p><strong>Est. Ship Date:</strong> ${formatDate(p.estimated_ship_date)}</p>
      <p><strong>Est. Delivery:</strong> ${formatDate(p.estimated_delivery_date)}</p>
      ${
        p.ship_node
          ? `<p><strong>Ship Node:</strong> ${escape(p.ship_node.type)} (${escape(p.ship_node.id)})</p>`
          : ""
      }
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>SKU</th>
        <th>Product</th>
        <th class="num">Qty</th>
        <th>UoM</th>
        <th class="num">Unit Price</th>
        <th class="num">Line Total</th>
      </tr>
    </thead>
    <tbody>${linesHtml}</tbody>
  </table>

  <div class="totals">
    <table>
      <tr><td>Subtotal</td><td class="num">${formatCurrency(p.totals.subtotal)}</td></tr>
      <tr><td>Tax</td><td class="num">${formatCurrency(p.totals.tax_total)}</td></tr>
      <tr class="grand"><td>Grand Total</td><td class="num">${formatCurrency(p.totals.grand_total)}</td></tr>
    </table>
  </div>

  <div class="footer">
    Generated by DocFlow — AI Document Processing · DocFlow<br>
    Source: Walmart Marketplace API (marketplace.walmartapis.com)
  </div>
</body>
</html>`;
}

async function launchBrowser() {
  const executablePath = process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH;
  if (executablePath) {
    return playwrightChromium.launch({ executablePath, headless: true });
  }
  if (!process.env.VERCEL) {
    try {
      return await playwrightChromium.launch({ headless: true });
    } catch {
      // fall through to packaged
    }
  }
  return playwrightChromium.launch({
    args: chromium.args,
    executablePath: await chromium.executablePath(),
    headless: true,
  });
}

/**
 * Render a Walmart parsed order to PDF.
 * Returns null on failure (non-fatal — caller continues without PDF).
 */
export async function renderWalmartOrderToPdf(
  parsed: WalmartParsed,
): Promise<Buffer | null> {
  let browser: Awaited<ReturnType<typeof launchBrowser>> | null = null;
  try {
    browser = await launchBrowser();
    const context = await browser.newContext({ viewport: { width: 1056, height: 1400 } });
    const page = await context.newPage();
    const html = renderHtml(parsed);

    await page.setContent(html, { waitUntil: "networkidle", timeout: 15_000 });
    const pdf = await page.pdf({
      format: "Letter",
      printBackground: true,
      margin: { top: "0", bottom: "0", left: "0", right: "0" },
    });
    if (!pdf || pdf.length < 4 || pdf.subarray(0, 4).toString() !== "%PDF") {
      return null;
    }
    return Buffer.from(pdf);
  } catch (err) {
    console.warn("walmart_pdf_render_warning:", err);
    return null;
  } finally {
    if (browser) await browser.close().catch(() => {});
  }
}
